project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - Install_software.qmd
  - slides/welcome.qmd
  - slides/slides_1.qmd
  - slides/slides_2.qmd
  - slides/slides_3.qmd
  - slides/slides_intro_spatial.qmd
  - slides/slides_areal.qmd
  - slides/slides_geostats.qmd
  - slides/slides_points.qmd
  - slides/slides_spatioTemporal.qmd
  - slides/slides_Model_Comparison.qmd
  - slides/slides_multilik.qmd
  - practicals/LMM_ex.qmd
  - practicals/GLMM_fit.qmd
  - day2_practical_3.qmd
  - day2_practical_4.qmd
  - day3_practical_5.qmd
  - day4_practical_6.qmd
  - day4_practical_7.qmd
  - INLA_nutshell.qmd
  - references.qmd
website:
  title: "`inlabru` workshop"
  navbar:
    logo: Image/INLA_logo.png
    right:
    - text: GitHub
      href: https://github.com/ # replace with github repo URL
    left:
    - text: Home
      href: index.qmd
    - text: Installation
      href: Install_software.qmd
    - text: Slides
      menu:
      - text: Welcome to the Course 
        href: slides/welcome.qmd
      - text: Slides 1 - Introduction
        href: slides/slides_1.qmd
      - text: Slides 2 - The inlabru worflow
        href: slides/slides_2.qmd
      - text: Slides 3 - Temporal Models
        href: slides/slides_3.qmd
      - text: Slides 4 - Intro to spatial modeling
        href: slides/slides_intro_spatial.qmd
      - text: Slides 5 - Area Data
        href: slides/slides_areal.qmd
      - text: Lecture 6 - Geostatistics
        href: slides/slides_geostats.qmd
      - text: Lecture 7 - Point Processes 
        href: slides/slides_points.qmd
      - text: Slides 8 - Spatio-Temporal Models
        href: slides/slides_spatioTemporal.qmd
      - text: Slides 9 - Model Comparison
        href: slides/slides_Model_Comparison.qmd
      - text: Slides 10 - Multiple Likelihoods Models
        href: slides/slides_multilik.qmd
        
    - text: Practicals
      menu:
      - text: Practical 1 - Linear (Mixed) Models
        href: practicals/LMM_ex.qmd
      - text: Practical 2 - Generalised Linear (Mixed) Models
        href: practicals/GLMM_fit.qmd
      - text: Practical 3 - Temporal Models
        href: day2_practical_3.qmd
      - text: Practical 4 - Spatial Data Types
        href: day2_practical_4.qmd
      - text: Practical 5 - Spatial Models
        href: day3_practical_5.qmd
      - text: Practical 6 - Spatio-Temporal Models and Model Comparison
        href: day4_practical_6.qmd  
      - text: Practical 7 - Multiple Likelihoods Models
        href: day4_practical_7.qmd  
    - text: Supplementary Material
      href: INLA_nutshell.qmd
    - text: References
      href: references.qmd
format:
  html:
    theme: flatly
    respect-user-color-scheme: false
    css:
      - include/webex.css
      - styles.css
    include-after-body: include/webex.js
    toc: true
    toc-location: right
    toc-depth: 3    
execute:
  freeze: auto
