---
title: "`inlabru` workshop template"
subtitle: "D/M/Y  • City, Country<br>Jafet Belmont · Sara Martino · Janine Illian"
title-block-banner: "#00000000"
title-block-banner-color: "white"
format:
  html:
    css: styles.css
    body-classes: home-page
  PrettyPDF-pdf:
    keep-tex:  true
    number-sections: true
editor_options: 
  chunk_output_type: console
params:
  city: "CITY"
  country: "COUNTRY"
  year: 2026
  month: "MONTH"
  days: "1-4"
  base_url: "https://inlabru-courses.github.io/"
---


# Welcome to the course!

-   Welcome to the `inlabru` workshop!
-   The aim of this workshop is to . . .
-   Workshop materials are available in the github repository

::: {.callout-warning}
##  Important! ⚠️

 Please use the instructions provided [here](Install_software.qmd) to install and check your installation
  *before* the course starts.
:::

# Learning Objectives for the workshop

At the end of the workshop, participants will have an understanding of:

-   ILO1
-   ILO2
-   ILO3
-   ILO4

# Intended audience

The workshop aims to cater for participants with a range of different backgrounds, who are interested in analysing data with modern spatial and spatio-temporal statistical modelling approaches.

# Prerequisites

Participants should be familiar with the `R` environment, and general statistical approaches for modelling such as regression, analysis of (co)variance, and generalized linear models.

No knowledge of `R-INLA` or `inlabru` is required.

# Schedule {#schedule-tabs}



::: panel-tabset
### Day 1

: {.striped .hover}


| Time | Topic |
|:----------------------------------:|:----------------------------------:|
| 9:00 - 9:30   | [**Welcome  and  introduction to the course**](slides/welcome.html)  |
| 9:30 - 10:30  | [**Session 1**: Introduction to `inlabru`](slides/slides_1.html)  |
| 10:30 - 10:45 | Coffee break ☕ | 
| 10:45 - 12:00 | [Practical Session 1](practicals/LMM_ex.qmd)                    |
| 12:00 - 13:00 | [**Session 2**: The `inlabru` workflow](slides/slides_2.html)   |
| 13:00 - 14:30 |  Lunch 🍽️ |
| 14:30 - 15:30 | [Practical Session 2](practicals/GLMM_fit.qmd) |
| 15:30 - 15:45 | Coffee break ☕ |
| 15:45  - 17:00 | [**Session 3**: Time Series Models](slides/slides_3.html)|


### Day 2

: {.striped .hover}


| Time | Topic |
|:----------------------------------:|:----------------------------------:|
| 9:00 - 10:00  | [**Session 3 cont.**: Time Series Models](slides/slides_3.html) |
| 10:00 - 11:30 | [Practical Session 3](day2_practical_3.html) |
| 11:30 - 12:00 | Coffee break ☕ |
| 12:00 - 13:00 | [**Session 4**: Introduction to Spatial Statistics](slides/slides_intro_spatial.html) |
| 13:00 - 14:30 | Lunch 🍽️ |
| 14:30 - 15:30 |  [Practical Session 4](day2_practical_4.html) |
| 15:30 - 15:45 | Coffee break ☕ |
| 15:45 - 17:00 | [**Session 5**: Areal processes](slides/slides_areal.html) |


###	Day 3

: {.striped .hover}


| Time | Topic |
|:----------------------------------:|:----------------------------------:|
| 09:00 - 10:00 |  [**Session 6**: Geostatistics](slides/slides_geostats.html) |
| 10:00 - 11:30 |  [Practical Session 5](day3_practical_5.html) |
| 11:30 - 12:00 | Coffee break ☕ |
| 12:00 - 13:00 | [**Session 7**: Point Processes](slides/slides_points.html) |
| 13:00 - 14:30 | Lunch 🍽️ |
| 14:30 - 15:30 |  [Practical Session 5 (cont.)](day3_practical_5.html)| |
| 15:30- 15:45  | Coffee break ☕ |
| 15:45 - 17:00 | [**Session 8**: Spatiotemporal models](slides/slides_spatioTemporal.qmd)  |




### Day 4

: {.striped .hover}


| Time | Topic |
|:----------------------------------:|:----------------------------------:|
| 09:00 - 10:00 |  [**Session 9**: Model comparison and evaluation](slides/slides_Model_Comparison.qmd) |
| 10:00 - 11:30 |  [Practical Session 6](day4_practical_6.qmd) |
| 11:30 - 12:00 | Coffee break ☕ |
| 12:00 - 13:00 | [**Session 10**: Multi-likelihood/joint likelihood models](slides/slides_multilik.html)  |
| 13:00 - 14:30 | Lunch 🍽️ |
| 14:30 - 15:30 | [Closing session](slides/slides_Closing_Remarks.html) and discussion|
| 15:30- 17:00  | [Practical Session 7 &  General practice](day4_practical_7.qmd) |


:::


# Licence
[CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/)


# Citation


```{r}
#| echo: false
#| results: asis

date_full <- paste(params$days, params$month, params$year)
cite_key  <- paste0("Belmont", params$year, "inlabru")

bibtex <- sprintf(
'@Manual{%s,
  title  = {inlabruCourse%s%s: Course Materials for %s inlabru Course %s},
  author = {Belmont, Jafet and Martino, Sara and Illian, Janine},
  year   = {%s},
  url    = {%s}
}',
  cite_key, params$month, params$year, params$city, date_full,
  params$year, params$base_url
)

modal_html <- sprintf(
'<div class="modal fade" id="cite-info" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Citation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <pre><code class="language-bibtex">%s</code></pre>
      </div>
    </div>
  </div>
</div>', bibtex)

# wrap in a raw-HTML fence so Pandoc renders it as HTML, not text
cat("```{=html}\n", modal_html, "\n```\n", sep = "")
```


<button type="button" class="venue-info-link" data-bs-toggle="modal" data-bs-target="#cite-info">
::: venue-card
Belmont J., Martino S., Illian, J. F (`r params$year`). _inlabru Course `r params$month` `r params$year`: Course Materials for `r params$city` inlabru `r params$days` `r params$month` `r params$year`_.
`r params$base_url`
:::
</button>



# Contact {#sec-contact}

**UPDATE with git-specific discussion forum**
Questions about the workshop? Join the discussion on [GitHub Discussions space](`r params$base_url`)


